// AUTO-GENERATED by scripts/generate-tracks.mjs — do not edit by hand.
// Run `npm run gen:tracks` to regenerate the WAVs and this manifest together.

export type DemoTrack = {
  slug: string;
  title: string;
  artist: string;
  bpm: number;
  key: string;
  mood: string;
  src: string;         // primary (compressed OGG)
  srcFallback: string; // fallback (WAV)
  /** Seconds. */
  duration: number;
};

export const DEMO_TRACKS: DemoTrack[] = [
  {
    "slug": "subsurface",
    "title": "Subsurface",
    "artist": "Wavecore System",
    "bpm": 124,
    "key": "F minor",
    "mood": "Peak-time techno · tight 4/4 · sub-heavy",
    "src": "/tracks/subsurface.ogg",
    "srcFallback": "/tracks/subsurface.wav",
    "duration": 41.7
  },
  {
    "slug": "ion-drift",
    "title": "Ion Drift",
    "artist": "Wavecore System",
    "bpm": 84,
    "key": "D dorian",
    "mood": "Beatless intro · downtempo · wide pads",
    "src": "/tracks/ion-drift.ogg",
    "srcFallback": "/tracks/ion-drift.wav",
    "duration": 44
  },
  {
    "slug": "chromagrid",
    "title": "Chromagrid",
    "artist": "Wavecore System",
    "bpm": 146,
    "key": "A minor",
    "mood": "Breakbeat · dense arps · brightest highs",
    "src": "/tracks/chromagrid.ogg",
    "srcFallback": "/tracks/chromagrid.wav",
    "duration": 42.5
  }
];
